### ISSUE TITLE
M1 Mac - need to adjust Makefile

### ISSUE THREAD

**Issue by jam07912** [braineo/airport-bssid#7]
Hi,

On my M1 Mac I had to adjust the Makefile as follows:

".PHONY: install
install:
	ln -fs $(PWD)/.build/arm64-apple-macosx/debug/bssid /usr/local/bin/"

When you swift build on M1 architecture, it seems that the build folder name defaults to the one above, instead of the one in the original Makefile.

Maybe add that to the readme or so.

Cheers!

**Comment by braineo** [comment]
added in 6cae7a79e8cf06f9d5e8a7a8f930decfece41433
